### ISSUE TITLE
AfterWind's issue dump from his personal TODO list. upon learning about checkmarks in markdown.

### ISSUE THREAD

**Issue by AfterWind** [MyEssentials/MyTown2#141]
- [ ] Liquid flow in towns
- [ ] RaInBoW CoLoReD TeXt
- [ ] Notify flag trespassing with what they tried to trespass it with.
- [ ] Add all plots to the block's plot list
- [ ] Fix friends
- [ ] Friends will be able to bypass town protection if mayor or some kind of rank is their friends as well
- [ ] Schematics
- [ ] Per World configurations
- [ ] Scoreboard information about chunk/town
- [ ] Provide option for the block being dynamically changed without being broken in json files.
- [ ] Check if all the converters from double to int work properly, if not, make your own for maximum accuracy.
- [ ] Look at MCForum for not fixed issues.
- [ ] Automatically add protection through commands or something 
- [ ] Maybe make your own log file?
- [ ] Block place check and custom range from towns
- [ ] Right click and move might bypass some protection.
- [ ] Removal of BlockWhitelists
- [ ] Provide donation link
- [ ] Change welcome message etc.
- [ ] A way for players to BUY plots of land.
- [ ] Do something about loading invalid config files.
- [ ] Port most things to JSON files.
- [ ] Item Pickup counter improvement.
- [ ] Removing spawning areas so that mobs don't spawn in protected land
- [ ] Very retarted condition checking at ANDs and ORs
- [ ] Add dropped items protections
- [ ] Don't forget about entity pvp attackers list for JSON
- [ ] Exception when checking config is thrown instead of being changed to default when needed
- [ ] Command check is not done correctly
- [ ] Command for adding/subtracting extra chunks
- [ ] Command for automatic download of protections from GitHub.
- [ ] Permission string based check for mayor bypass and such.
- [ ] Protect against people leaving the plot empty
- [ ] Give protection bypass for entities that use FakePlayer (ex: Golems from TC)
- [ ] Cost for teleporting to another town (/t spawn town)
- [ ] Move fields to top for any class aside from static
- [ ] Allow accessBlocks flag to check on left click as well.
